import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavWrapper from "./ui/nav-bar";
import { HomeLogo } from "./ui/logo";
const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <nav className="bg-gray-800 flex items-center justify-between px-4">
            <HomeLogo/>
            <NavWrapper/>
          </nav>
        </header>
        <div>
          {children}
        </div>
      </body>
    </html>
  );
}
